walkmod-serializable-plugin
===========================
Raquel Pau <raquelpau@gmail.com>

This is a walkmod plugin to add "implements java.io.Serializable" in all Java classes (root and nested). 

== Example
Let's see an example. Take a look to this code. This is a class that does not implement Serializable
```java
package example;

public class Foo{
  void hello(){
    ...
  }
}
```

What this plugins generates is the following modified code:
```java
package example;

public class Foo implements java.io.Serializable{
  void hello(){
    ...
  }
}
```

== Usage

. Add the https://github.com/rpau/walkmod-maven-plugin[walkmod-maven-plugin] into your `walkmod.xml` as a configuration provider. 
This component will interpret your classpath accoding your `pom.xml` and will build your project.

. Add the transformation `serializable` into your  `walkmod.xml`

```XML
<!DOCTYPE walkmod PUBLIC "-//WALKMOD//DTD"  "http://www.walkmod.com/dtd/walkmod-1.1.dtd" >
<walkmod>
 
  <conf-providers>
    <conf-provider type="maven"></conf-provider>
  </conf-providers>
  <chain name="default"> 
    <transformation type="serializable"/>
  </chain>  
</walkmod>
```

You can apply walkmod-serializable-plugin via walkmod. 

  $ walkmod apply

Or, you can also check which would be the modified classes typing:

  $ walkmod check
  
== Contributing

If you want to hack on this, fork it, improve it and send me a pull request.

To get started using it, just clone it and call mvn install. 


